import * as dotenv from 'dotenv';
dotenv.config();

import { EpisodicMemory } from '../memory/memory.js';
import { ProceduralMemory } from '../memory/procedural.js';
import { MemoryConsolidator } from '../memory/consolidation.js';
import { Scheduler } from '../background/scheduler.js';
import { createLLMProvider } from '../providers/llmProvider.js';
import * as fs from 'fs/promises';
import * as path from 'path';

const DB_PATH = './test_phase5.db';
const SKILLS_DIR = './test_phase5_skills';

async function cleanup() {
  try {
    await fs.unlink(DB_PATH);
  } catch (e) {}
  try {
    await fs.rm(SKILLS_DIR, { recursive: true, force: true });
  } catch (e) {}
}

async function runTests() {
  console.log('=== STARTING PHASE 5 SCHEDULER & CONSOLIDATION TESTS ===\n');
  await cleanup();

  if (!process.env.GEMINI_API_KEY) {
    console.error('ERROR: GEMINI_API_KEY is not defined in the environment variables. Skipping.');
    process.exit(1);
  }

  // Initialize directory
  await fs.mkdir(SKILLS_DIR, { recursive: true });

  const provider = createLLMProvider('gemini');
  const memory = new EpisodicMemory(DB_PATH);
  await memory.init();
  const procedural = new ProceduralMemory(SKILLS_DIR);

  // ----------------------------------------------------
  // TEST 1: Memory & Skills Consolidation (Agent Growth)
  // ----------------------------------------------------
  console.log('--- TEST 1: Memory & Skills Consolidation ---');
  
  // Save 10 mock episodic messages (5 turns)
  const sessionId = 'test-session-1';
  
  // Turn 1
  await memory.saveMessage(sessionId, 'user', [{ text: 'Hello Athena, my name is Raghu and I love coding in Rust.' }]);
  await memory.saveMessage(sessionId, 'model', [{ text: 'Hi Raghu! That is great to hear. Rust is a very powerful language.' }]);

  // Turn 2
  await memory.saveMessage(sessionId, 'user', [{ text: 'Can you write down instructions on how I usually compile Rust releases?' }]);
  await memory.saveMessage(sessionId, 'model', [{ text: 'Sure! Please tell me your compilation steps.' }]);

  // Turn 3
  await memory.saveMessage(sessionId, 'user', [{ text: 'First you run cargo check, then you run cargo build --release to build a release binary.' }]);
  await memory.saveMessage(sessionId, 'model', [{ text: 'Understood. I will remember this compile procedure.' }]);

  // Turn 4
  await memory.saveMessage(sessionId, 'user', [{ text: 'Also, my database server port is 9988.' }]);
  await memory.saveMessage(sessionId, 'model', [{ text: 'Saved. The database port is 9988.' }]);

  // Turn 5
  await memory.saveMessage(sessionId, 'user', [{ text: 'What is the compilation procedure for Rust?' }]);
  await memory.saveMessage(sessionId, 'model', [{ text: 'To compile: first run cargo check, then run cargo build --release.' }]);

  const initialUnconsolidated = await memory.getUnconsolidatedCount();
  console.log(`Initial unconsolidated count: ${initialUnconsolidated}`);
  if (initialUnconsolidated !== 10) {
    throw new Error(`Expected 10 unconsolidated records, got ${initialUnconsolidated}`);
  }

  const consolidator = new MemoryConsolidator(
    memory,
    procedural,
    provider,
    SKILLS_DIR,
    process.env.GEMINI_MODEL || 'gemini-2.5-flash'
  );

  console.log('Running memory consolidation...');
  const result = await consolidator.consolidate();
  console.log('Consolidation result:', JSON.stringify(result, null, 2));

  const postUnconsolidated = await memory.getUnconsolidatedCount();
  console.log(`Post unconsolidated count: ${postUnconsolidated}`);
  if (postUnconsolidated !== 0) {
    throw new Error(`Expected 0 unconsolidated records, got ${postUnconsolidated}`);
  }

  // Verify semantic memory facts search
  console.log('Searching semantic facts for Raghu...');
  const facts = await memory.searchSemanticFacts('What is the user name and their favorite language?', 3, 0.5);
  console.log('Extracted semantic facts found:', JSON.stringify(facts, null, 2));
  const hasRaghuOrRust = facts.some(f => f.fact.toLowerCase().includes('raghu') || f.fact.toLowerCase().includes('rust') || f.fact.toLowerCase().includes('9988'));
  if (!hasRaghuOrRust) {
    console.warn('WARNING: Gemini consolidation did not extract Raghu/Rust/9988 fact, but this can be prompt-sensitive.');
  } else {
    console.log('✓ Fact consolidation verified successfully.');
  }

  // Verify skills file creation
  const skills = await fs.readdir(SKILLS_DIR);
  console.log('Created skills files:', skills);
  if (skills.length === 0) {
    console.warn('WARNING: No skill files were generated by consolidation. This can be prompt-sensitive.');
  } else {
    const skillContent = await fs.readFile(path.join(SKILLS_DIR, skills[0]), 'utf-8');
    console.log(`Skill File Content (${skills[0]}):\n${skillContent}`);
    if (!skillContent.includes('---') || !skillContent.includes('name:')) {
      throw new Error('Skill file format is invalid.');
    }
    console.log('✓ Skill consolidation verified successfully.');
  }

  // ----------------------------------------------------
  // TEST 2: Scheduler tick and execution
  // ----------------------------------------------------
  console.log('\n--- TEST 2: Scheduler and Cron Triggers ---');

  const scheduler = Scheduler.getInstance();
  scheduler.setMemory(memory);

  let runnerCalled = false;
  let notifierCalled = false;
  let runningPrompt = '';
  let runningSession = '';

  scheduler.setRunner(async (prompt, sessionId) => {
    runnerCalled = true;
    runningPrompt = prompt;
    runningSession = sessionId;
    return 'Execution output from mocked runner';
  });

  scheduler.setNotifier(async (sessionId, result) => {
    notifierCalled = true;
    if (result.includes('Execution output')) {
      console.log(`✓ Notifier called with result: "${result}"`);
    } else {
      throw new Error(`Notifier received wrong result: ${result}`);
    }
  });

  // Add job
  console.log('Adding cronjob for testing...');
  const job = await scheduler.addJob('test-job-1', 'Clean database logs', '*/5 * * * *', 'telegram_12345');
  console.log(`Added job. Next run at: ${new Date(job.nextRun).toISOString()}`);

  // Mock nextRun to trigger immediately
  const now = Date.now();
  await memory.updateScheduledJobRun(job.id, null, now - 1000);

  // Trigger tick
  console.log('Triggering scheduler tick...');
  await scheduler.tick();

  // Wait a short moment for async callbacks to finish
  await new Promise(resolve => setTimeout(resolve, 500));

  if (!runnerCalled) {
    throw new Error('Scheduler runner was not called.');
  }
  if (!notifierCalled) {
    throw new Error('Scheduler notifier was not called.');
  }
  if (runningPrompt !== 'Clean database logs' || runningSession !== 'telegram_12345') {
    throw new Error(`Runner received wrong prompt or session: ${runningPrompt}, ${runningSession}`);
  }
  console.log('✓ Scheduler execution and callbacks verified successfully.');

  // Verify DB state updated
  const jobs = await scheduler.listJobs();
  const updatedJob = jobs.find(j => j.id === 'test-job-1')!;
  console.log(`Updated job last run: ${updatedJob.lastRun ? new Date(updatedJob.lastRun).toISOString() : 'never'}`);
  console.log(`Updated job next run: ${new Date(updatedJob.nextRun).toISOString()}`);
  if (!updatedJob.lastRun || updatedJob.nextRun <= now) {
    throw new Error('Job lastRun or nextRun did not update correctly in DB.');
  }
  console.log('✓ Scheduler database state updates verified successfully.');

  // Clean up
  await memory.close();
  await cleanup();
  console.log('\nALL PHASE 5 TESTS PASSED SUCCESSFULLY! 🎉');
}

runTests().catch(async (err) => {
  console.error('\n❌ TEST RUN FAILED:', err);
  await cleanup();
  process.exit(1);
});
